name: SonarCloud Scan - dcm4che-core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: Run SonarCloud analysis and export report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build only dcm4che-core module
        run: mvn clean install -DskipTests

      - name: Run SonarCloud analysis using Maven plugin on dcm4che-core
        working-directory: dcm4che-core
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=sonamsuragini1_dcm4che2 \
            -Dsonar.organization=sonamsuragini1 \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.projectBaseDir=$(pwd) \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=main

      - name: Generate SonarCloud report
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mkdir -p report
          curl -s -u $SONAR_TOKEN: \
            "https://sonarcloud.io/api/measures/component?component=sonamsuragini1_dcm4che2&metricKeys=bugs,vulnerabilities,code_smells,coverage,duplicated_lines_density" \
            -o report/sonar-report.json

          echo "## SonarCloud Summary" > report/sonar-report.md
          echo "\`\`\`json" >> report/sonar-report.md
          cat report/sonar-report.json >> report/sonar-report.md
          echo "\`\`\`" >> report/sonar-report.md

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-report
          path: report/
